# 服务器数据来源：https://www.bilibili.com/video/BV1EE411B7SU?p=10
# 用老师搭的接口的请注意同学注意，请不要乱删数据，删了请加回去，删的时候请留个一两条在列表里。特别是角色权限部分，删光了权限数据那做到这部分的同学就没法继续做下去了。。。
# 另外给个提示，遇到没有数据的情况，可以去老师的项目网站里加一些数据进去。。。
# 前端项目地址：http://shop.liulongbin.top/
# 后端接口地址：https://www.liulongbin.top:8888/api/private/v1/
server:
  test: http://127.0.0.1:8888/api/private/v1/
  dev: https://www.liulongbin.top:8888/api/private/v1/

response_reg:
  # 提取token的jsonpath表达式
  token: $.data.token
  # 提取响应的断言数据jsonpath表达式
  response: $.meta

file_path:
  case_data: ../data/case_data.xlsx
  report_data: ../report/data/
  report_generate: ../report/html/
  report_zip: ../report/html/apiAutoTestReport.zip
  log_path: ../log/运行日志.log

email:
  # 发件人邮箱
  user:  123456.com
  # 发件人邮箱授权码
  password:  ASGCSFSGS
  # 邮箱host
  host:  smtp.163.com
  contents:  解压apiAutoReport.zip(接口测试报告)后，请使用已安装Live Server 插件的VsCode，打开解压目录下的index.html查看报告
  # 收件人邮箱
  addressees:  ["收件人邮箱1","收件人邮箱2","收件人邮箱3"]
  title:  接口自动化测试报告(见附件)
  # 附件地址
  enclosures: ["../report/html/apiAutoTestReport.zip",]

