server:
  test: http://127.0.0.1:8888/api/private/v1/
  dev: http://47.115.124.102:8888/api/private/v1/

response_reg:
  # 提取token的表达式
  token: $.data.token
  # 提取响应的断言数据
  response: $.meta

file_path:
  case_data: ../data/case_data.xlsx
  report_data: ../report/data/
  report_generate: ../report/html/
  report_zip: ../report/html/apiAutoTestReport.zip
  log_path: ../log/运行日志{time}.log

email:
  # 发件人邮箱
  user:  123456.com
  # 发件人邮箱授权码
  password:  ASGCSFSGS
  # 邮箱host
  host:  smtp.163.com
  contents:  解压apiAutoReport.zip(接口测试报告)后，请使用已安装Live Server 插件的VsCode，打开解压目录下的index.html查看报告
  # 收件人邮箱
  addressees:  ["收件人邮箱1","收件人邮箱2","收件人邮箱3"]
  title:  接口自动化测试报告(见附件)
  # 附件地址
  enclosures: ["../report/html/apiAutoTestReport.zip",]

